### ISSUE TITLE
Windows 11 with both KiCAD5/6/7/8 generate_netlist and generate_svg fail

### ISSUE THREAD

**Issue by GinGawnKwong** [devbisme/skidl#235] opened 2024-12-11 13:43 UTC
### Discussed in https://github.com/devbisme/skidl/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **GinGawnKwong** December 11, 2024</sup>
```
here is a demo code from the document 
from skidl import *

# Create part templates.
q = Part("Device", "Q_PNP_CBE", dest=TEMPLATE)
r = Part("Device", "R", dest=TEMPLATE)

# Create nets.
gnd, vcc = Net("GND"), Net("VCC")
a, b, a_and_b = Net("A"), Net("B"), Net("A_AND_B")

# Instantiate parts.
gndt = Part("power", "GND")             # Ground terminal.
vcct = Part("power", "VCC")             # Power terminal.
q1, q2 = q(2)                           # Two transistors.
r1, r2, r3, r4, r5 = r(5, value="10K")  # Five 10K resistors.

# Make connections between parts.
a & r1 & q1["B C"] & r4 & q2["B C"] & a_and_b & r5 & gnd
b & r2 & q1["B"]
q1["C"] & r3 & gnd
vcc += q1["E"], q2["E"], vcct
gnd += gndt

# generate_schematic()
generate_netlist(tool=KICAD6)   # Create KICAD version 6 netlist.
# Create KICAD version 8 netlist.
```

In this demo,it show up with error :ERROR: No footprint for GND/#PWR1. @ [f:\GDUT\EDA\skidl-master\mytest\mytest_1.py:25]
![image](https://github.com/user-attachments/assets/3f7259f8-cdeb-4115-8403-b0b43afb2164)
I had set the KICAD6/7/8's symbol_dir right, but in the nest demo it just ran succeeded.but the generate_svg still fail
```
from skidl import *

# Create input & output voltages and ground reference.
vin, vout, gnd = Net('VI'), Net('VO'), Net('GND')

# Create two resistors.
r1, r2 = 2 * Part("Device", 'R', TEMPLATE, footprint='Resistor_SMD.pretty:R_0805_2012Metric')
r1.value = '1K'   # Set upper resistor value.
r2.value = '500'  # Set lower resistor value.

# Connect the nets and resistors.
vin += r1[1]      # Connect the input to the upper resistor.
gnd += r2[2]      # Connect the lower resistor to ground.
vout += r1[2], r2[1] # Output comes from the connection of the two resistors.

# Or you could do it with a single line of code:
# vin && r1 && vout && r2 && gnd

# Output the netlist to a file.
generate_netlist(tool=KICAD6)
generate_svg()
# generate_schematic()
```</div>

**Comment by devbisme** [comment] 2024-12-12 00:42
Fixed in release 2.0.1.

**Closed by devbisme** 2024-12-12 00:42 UTC

**Comment by cyberhuman** [comment] 2025-01-29 14:23
After updating to 2.0.1, I noticed my existing code doesn't produce many netlist names anymore.
The minimal reproducer is:
```py
RR = Part('Device', 'R', value='1k')
SW = Part('Switch', 'SW_DPST')

#SW[1] & SW[2]
SW[3] & SW[4]

gnd = Net('GND')

RR[1] & SW[1, 3] & gnd
RR[2] & gnd

generate_netlist()
```
In the netlist, the GND net is named N$1 instead of GND. Any clue what's causing this?
This particular circuit isn't exactly correct, but the net names should still be correct?
I will try to find another reproducer with a better circuit since other networks not connected to SW are also affected.

**Comment by devbisme** [comment] 2025-01-29 14:48
I'll look into this.

**Comment by cyberhuman** [comment] 2025-01-29 14:54
It looks like it's order-dependent. If a named net is added later than automatic net was created, the name is not propagated properly.

```py
RR = Part('Device', 'R', dest=TEMPLATE)
RR1 = RR(value='1M')
RR2 = RR(value='2M')
RR3 = RR(value='3M')

(RR1 & RR2) | RR3 # results in `N$2` and `N$3`
RR1[1] += Net('net1')
RR2[2] += Net('net2')
#(RR1 & RR2) | RR3 # results in `net1` and `net2`

generate_netlist()
```

**Comment by devbisme** [comment] 2025-01-30 18:31
I have a fix for this in the `development` branch. Give it a try and see if it works for you.

**Comment by cyberhuman** [comment] 2025-01-31 11:00
Tested and works great! Thank you!
